### ISSUE TITLE
Introduction to Docker InfraKit

### ISSUE THREAD

**Issue by drmdrew** [DockerOttawaMeetup/ideas#10]
I'd like to see an overview and some show-and-tell of InfraKit:

https://github.com/docker/infrakit

> InfraKit is a toolkit for creating and managing declarative, self-healing infrastructure. It breaks infrastructure automation down into simple, pluggable components. These components work together to actively ensure the infrastructure state matches the user's specifications. Although InfraKit emphasizes primitives for building self-healing infrastructure, it also can be used passively like conventional tools.

**Comment by hairyhenderson** [comment]
@drmdrew I think we still need the slides uploaded to the github.com/DockerOttawaMeetup/Slides repo 😉 

Going to close this though, since it was already delivered!
