### ISSUE TITLE
Overview of the Latest Release of docker 

### ISSUE THREAD

**Issue by dublinbay** [DockerOttawaMeetup/ideas#11]
Overview of the Latest Release of docker

**Comment by dublinbay** [comment]
Using resources provide by Docker I think this will be possible to do in the March meetup.

**Comment by jimareed** [comment]
That is a great idea!  Docker has a special meetup planned in March for their 4th Birthday.  They suggested we do a New Release Meetup in Feb.  Would you be interested in presenting in Feb?  I suspect they will prepare a slide deck.

**Comment by dublinbay** [comment]
As long as I can get the material from the Docker team, I have no problem doing this for the Feb meetup.

**Comment by hairyhenderson** [comment]
@dublinbay FYI the info is available now in https://github.com/docker/community/blob/master/Docker-Meetup-Content/Docker%201.13.md
