### ISSUE TITLE
Docker Storage

### ISSUE THREAD

**Issue by daneroo** [DockerOttawaMeetup/ideas#13]
Present the motivation and demonstrate the use of docker volumes, in the context of multiple hosts.

**Comment by hairyhenderson** [comment]
@daneroo - can you post the link to your slides?

**Comment by daneroo** [comment]
They are posted here: https://github.com/DockerOttawaMeetup/Slides/tree/master/2017-01-25-Docker-Storage

**Comment by daneroo** [comment]
Just README.md with to slides.com and supporting repo

**Comment by hairyhenderson** [comment]
Ah thanks! I missed that :)
