### ISSUE TITLE
Using ENTRYPOINTs for fun and profit!

### ISSUE THREAD

**Issue by hairyhenderson** [DockerOttawaMeetup/ideas#2]
Ok, maybe not so much _fun_... :wink:

I'm thinking about doing a talk about a common pattern used in Docker images - the _entrypoint pattern_.

I'd cover things like:
- what the `ENTRYPOINT` instruction _is_
- where you'd use it
- where you wouldn't use it
- how to write a good entrypoint script

**Comment by daneroo** [comment]
+1, I think that focused, specificl topics like this are a great idea.

**Comment by hairyhenderson** [comment]
I'll be giving this talk at the July meetup in a couple days.

**Comment by hairyhenderson** [comment]
This talk was delivered at the July meetup. Closing the issue!
