### ISSUE TITLE
Platform as a Service via Mesos/Marathon

### ISSUE THREAD

**Issue by nicbet** [DockerOttawaMeetup/ideas#9]
Self healing, resource aware execution of docker containers over compute clusters via Mesos Marathon.

**Comment by hairyhenderson** [comment]
@nicbet - do you want to deliver this talk for the October meetup? (Oct. 26th)

**Comment by nicbet** [comment]
@hairyhenderson my schedule for this month is pretty tight. I'd prefer to push this to the November meetup.

**Comment by hairyhenderson** [comment]
No worries, @nicbet!
